version: '3.8'
services:
  jenkins:
    build:
      context: ../docker
      dockerfile: dockerfile
    privileged: true
    restart: always
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    networks:
      sonarqube-postgres:
        ipv4_address: 172.20.0.11
networks:
  sonarqube-postgres:
    name: sonarqube-postgres
